# Generated by Django 5.2.10 on 2026-07-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('followed_you', 'Followed you'), ('joke_published', 'Your joke was published'), ('joke_removed', 'Your joke was removed'), ('joke_rejected', 'Your submission was rejected')], max_length=32),
        ),
    ]
