# Generated by Django 5.2.10 on 2026-08-03 21:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('followed_you', 'Followed you'), ('joke_published', 'Your joke was published'), ('joke_removed', 'Your joke was removed'), ('joke_rejected', 'Your submission was rejected'), ('appeal_resolved', 'Your appeal was resolved')], max_length=32),
        ),
    ]
