# Generated by Django 5.2.17 on 2026-10-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_notification_data_encoder_and_appeal_resolved_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('followed_you', 'Followed you'), ('joke_published', 'Your joke was published'), ('joke_removed', 'Your joke was removed'), ('joke_rejected', 'Your submission was rejected'), ('appeal_resolved', 'Your appeal was resolved'), ('community_formed', 'A community you belong to formed')], max_length=32),
        ),
    ]
