"""
Django settings for JokesForProject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# In production (DEBUG=False) a real key MUST be provided via env — a missing
# key would otherwise silently sign JWTs with a publicly-known fallback.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable is required when DEBUG=False')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Required by dj-rest-auth
    'rest_framework_simplejwt.token_blacklist',  # For refresh token blacklisting
    'dj_rest_auth',
    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
    'drf_spectacular',
    'corsheaders',
    'pgtrigger',
    'anymail',
    # Local apps
    'jokes',
    'notifications',
    'creator_insights',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files directly from the app process —
    # avoids needing a CDN/bucket for the admin's CSS/JS in low-traffic deploys.
    # Must be placed immediately after SecurityMiddleware per WhiteNoise docs.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'JokesForProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JokesForProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# When DATABASE_URL is set (e.g. Neon), parse it and pass any libpq query-string
# params (sslmode, channel_binding, application_name, ...) through OPTIONS.
# Otherwise fall back to the individual DB_* vars used for local development.

def _build_default_db():
    url = os.getenv('DATABASE_URL', '').strip()
    if not url:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'jokesfor'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }

    parsed = urlparse(url)
    options = {k: v[-1] for k, v in parse_qs(parsed.query).items()}
    config: dict[str, Any] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': (parsed.path or '/').lstrip('/'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port) if parsed.port else '',
        'OPTIONS': options,
    }
    # Pooled hosts (PgBouncer transaction mode, e.g. Neon `-pooler`) don't
    # support server-side cursors — connections get reassigned mid-statement.
    if '-pooler' in (parsed.hostname or ''):
        config['DISABLE_SERVER_SIDE_CURSORS'] = True
    return config


DATABASES = {'default': _build_default_db()}


# Cache — Django DatabaseCache on the existing Postgres connection.
#
# DRF throttling reads/writes the `default` cache alias. Without this block,
# Django falls back to a per-process LocMemCache, so each gunicorn worker (and
# each Cloud Run instance) keeps its OWN throttle counters and the anon/user/
# verification_resend limits are bypassable by ~workers x instances.
#
# We use DatabaseCache (not Redis/Memcached) on purpose: it reuses the Neon
# connection we already hold, is strongly consistent, survives instance churn,
# and needs NO extra service or background worker — honoring the single-app,
# no-worker principle. The cache table is created by a migration (see
# notifications/migrations/0002_create_cache_table.py) so it exists in prod and
# in the test DB after `migrate`.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'jokesfor_cache',
        # Cap the table so it self-prunes; throttle entries are short-lived.
        'OPTIONS': {'MAX_ENTRIES': 10000, 'CULL_FREQUENCY': 3},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads + generated share cards).
# Local dev/test serve from the filesystem; production overrides the default
# storage to Google Cloud Storage when GS_BUCKET_NAME is set (see below).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


def build_default_storage(bucket_name: str) -> dict[str, Any]:
    """Return the STORAGES['default'] config.

    With GS_BUCKET_NAME set -> Google Cloud Storage (durable prod storage).
    Without it -> the filesystem (local dev + tests need no GCS).

    The bucket uses Uniform bucket-level access set to public-read, so we keep
    default_acl=None and querystring_auth=False: django-storages then returns a
    stable, non-expiring https://storage.googleapis.com/<bucket>/<path> URL.
    Signed URLs are deliberately avoided -- Cloud Run's default service account
    cannot V4-sign without the IAM Credentials API, and share cards must be
    crawler-fetchable (Open Graph) without expiry.
    """
    bucket_name = (bucket_name or '').strip()
    if not bucket_name:
        return {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

    options: dict[str, Any] = {
        'bucket_name': bucket_name,
        'default_acl': None,
        'querystring_auth': False,
        'file_overwrite': True,
    }
    project_id = os.getenv('GS_PROJECT_ID', '').strip()
    if project_id:
        options['project_id'] = project_id
    location = os.getenv('GS_LOCATION', '').strip()
    if location:
        options['location'] = location
    return {
        'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
        'OPTIONS': options,
    }


# Hashed + gzipped static assets so WhiteNoise can serve them with far-future
# cache headers (filename embeds content hash → safe to cache forever).
STORAGES = {
    'default': build_default_storage(os.getenv('GS_BUCKET_NAME', '')),
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'verification_resend': '3/15min',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
}


# drf-spectacular settings
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    'TITLE': 'Jokes For API',
    'DESCRIPTION': 'API for discovering and searching jokes',
    'VERSION': '1.0.0',
}


# django-cors-headers settings
# https://github.com/adamchainz/django-cors-headers

# For credentials mode (cookies), must specify exact origins - not wildcard.
# Comma-separated env var overlays the local-dev defaults so production can add
# its frontend origin (e.g. https://app.jokesfor.com) without a code change.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite dev server
    'http://127.0.0.1:5173',
] + [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True  # Required for httpOnly cookie auth

# CSRF: when behind Cloud Run / any TLS-terminating proxy, Django must trust
# the origin header. Same env-overlay pattern as CORS.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Cloud Run terminates TLS at the load balancer and forwards X-Forwarded-Proto.
# Without this, request.is_secure() returns False inside the container and
# `JWT_AUTH_SECURE` cookies would be silently dropped by the browser.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# When the frontend lives on a different eTLD+1 than the API (e.g. *.web.app
# frontend talking to *.run.app backend), JWT_COOKIE_SAMESITE=None is required
# so cookies cross the origin boundary. Browsers reject SameSite=None without
# Secure=True, so we mirror that pairing onto Django's other cookies in prod.
_COOKIE_SAMESITE = os.getenv('JWT_COOKIE_SAMESITE', 'Lax')
if _COOKIE_SAMESITE == 'None':
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Transport security — production only. Local dev runs over plain http, so these
# stay OFF when DEBUG=True. SECURE_PROXY_SSL_HEADER (set above) lets Django see
# Cloud Run's terminated TLS, so SECURE_SSL_REDIRECT won't loop.
if not DEBUG:
    # Start lower (e.g. 3600) on first prod rollout, then ramp to a year before
    # adding the domain to the browser HSTS preload list.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_SSL_REDIRECT = False
    SECURE_CONTENT_TYPE_NOSNIFF = False


# dj-rest-auth settings
# https://dj-rest-auth.readthedocs.io/en/latest/configuration.html

# 'Lax' works when frontend and API share an eTLD+1 (or for same-origin dev).
# Set JWT_COOKIE_SAMESITE=None in production when the frontend lives on a
# different domain from the Cloud Run URL — browsers won't send Lax cookies
# on cross-site fetches. SameSite=None requires Secure=True (Cloud Run is HTTPS).
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jokes-access-token',
    'JWT_AUTH_REFRESH_COOKIE': 'jokes-refresh-token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SECURE': not DEBUG,  # True in production (HTTPS), False for local dev
    'JWT_AUTH_SAMESITE': os.getenv('JWT_COOKIE_SAMESITE', 'Lax'),
    'SESSION_LOGIN': False,  # Disable session auth, use JWT only
    'REGISTER_SERIALIZER': 'JokesForProject.serializers.EmailOnlyRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'JokesForProject.serializers.JokesForUserDetailsSerializer',
}


# Simple JWT settings
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Email backend is environment-driven. Local dev prints to console (read the
# 6-digit code from stdout). Prod sets EMAIL_BACKEND=anymail.backends.resend.EmailBackend.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
ANYMAIL = {'RESEND_API_KEY': os.getenv('RESEND_API_KEY', '')}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Jokes For <noreply@localhost>')

# Registration email verification (the notifications app).
# EMAIL_VERIFICATION_REQUIRED is the deploy gate: keep False until a real email
# provider + verified domain are live, else new users cannot receive their code.
EMAIL_VERIFICATION_REQUIRED = os.getenv('EMAIL_VERIFICATION_REQUIRED', 'false').lower() == 'true'
EMAIL_VERIFICATION_CODE_TTL_MINUTES = int(os.getenv('EMAIL_VERIFICATION_CODE_TTL_MINUTES', '10'))
EMAIL_VERIFICATION_MAX_ATTEMPTS = int(os.getenv('EMAIL_VERIFICATION_MAX_ATTEMPTS', '5'))

# django-allauth settings
# https://docs.allauth.org/en/latest/account/configuration.html

ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for login
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Email required, no username
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable for development, 'mandatory' for production
ACCOUNT_UNIQUE_EMAIL = True

# Google OAuth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Google OAuth credentials (from environment)
GOOGLE_OAUTH_CALLBACK_URL = os.getenv('GOOGLE_OAUTH_CALLBACK_URL', 'http://localhost:5173/auth/google/callback')

# Error monitoring — Sentry, opt-in via SENTRY_DSN. No DSN => fully no-op, so
# local dev and the test suite never phone home. send_default_pii=False keeps
# user identifiers out of events (COPPA/GDPR posture).
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0')),
        send_default_pii=False,
        environment=os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )

