# Generated by Django 5.2.17 on 2026-10-04 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jokes', '0038_versioned_audience_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='✨', max_length=8)),
                ('color', models.CharField(default='#6A1CF6', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('is_listed', models.BooleanField(default=True, help_text='Unlisted communities are hidden from the directory and creator tools.')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='jokes.contexttag')),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['tag__name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'community'), name='communities_unique_membership')],
            },
        ),
    ]
