# Generated by Django 5.2.17 on 2026-10-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_backfill_theme_communities'),
        ('jokes', '0038_versioned_audience_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('like', 'Laugh reaction'), ('favorite', 'Favorite'), ('save', 'Save'), ('share', 'Signed-in share')], max_length=8)),
                ('source_id', models.BigIntegerField(help_text='Primary key of the ledger row this mirrors.')),
                ('occurred_at', models.DateTimeField()),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['occurred_at'], name='communities_signal_at'), models.Index(fields=['user', 'joke', 'kind'], name='communities_signal_pair')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'source_id'), name='communities_unique_signal_source')],
            },
        ),
    ]
