# Generated by Django 5.2.17 on 2026-10-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_backfill_community_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('cooling', 'Cooling')], max_length=8)),
                ('observed_at', models.DateTimeField(help_text='When the aggregate that set this status was computed.')),
                ('active_since', models.DateTimeField(blank=True, help_text='Start of the current (or most recent) active period.', null=True)),
                ('inactive_since', models.DateTimeField(blank=True, help_text='When it last stopped being active; null while active.', null=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When "community formed" notifications last went out.', null=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='communities.community')),
            ],
        ),
    ]
