# Generated by Django 5.2.17 on 2026-09-27 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('simulated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=280)),
                ('color', models.CharField(max_length=7)),
                ('emoji', models.CharField(max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('punchline', models.CharField(max_length=400)),
                ('format', models.CharField(default='text', max_length=20)),
                ('creator', models.CharField(max_length=80)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_lab.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], max_length=8)),
                ('updated_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_lab.participant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_lab.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'subject'), name='lab_unique_membership')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('request_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_lab.content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_lab.event')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_lab.participant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_lab.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['subject', 'occurred_at'], name='community_l_subject_1524c8_idx')],
            },
        ),
    ]
