# Generated by Django 5.2.10 on 2026-06-19 14:19

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], db_index=True, default='success', max_length=16)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'outcome'], name='audit_audit_action_91dcd3_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='auditlog',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5d6ea98f2d06c3401a026f07d96e29ee1cc8e78b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e464f', table='audit_auditlog', when='BEFORE')),
        ),
    ]
