# Generated by Django 5.2.10 on 2026-01-10 23:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_add_pgtrgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='joke',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='joke_search_vector_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='joke',
            trigger=pgtrigger.compiler.Trigger(name='joke_search_vector_update', sql=pgtrigger.compiler.UpsertTriggerSql(execute='tsvector_update_trigger("search_vector", "pg_catalog.english", "text", "setup", "punchline")', func='', hash='8a77c95a97a19b6f0137ae144278caf7895f588e', operation='INSERT OR UPDATE OF "text", "setup", "punchline"', pgid='pgtrigger_joke_search_vector_update_cde25', table='jokes_joke', when='BEFORE')),
        ),
    ]
