# Generated by Django 5.2.10 on 2026-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_jokerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='share_image',
            field=models.ImageField(blank=True, help_text='Auto-generated share card image for social media', upload_to='share-cards/'),
        ),
    ]
