# Generated by Django 5.2.10 on 2026-01-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_joke_share_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('copy', 'Copy to Clipboard'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='jokes.joke')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous shares', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['joke', 'created_at'], name='jokes_share_joke_id_8ddd8a_idx'), models.Index(fields=['platform', 'created_at'], name='jokes_share_platfor_0123a5_idx')],
            },
        ),
    ]
