# Generated by Django 5.2.10 on 2026-04-13 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_shareevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon name (e.g., bookmark, diamond, flame)', max_length=50)),
                ('criteria_type', models.CharField(help_text='Metric type: save_count, streak_days, share_count, favorite_count, rating_count', max_length=50)),
                ('criteria_value', models.IntegerField(default=1, help_text='Threshold to unlock')),
            ],
            options={
                'ordering': ['criteria_value'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this collection is visible to other users'),
        ),
        migrations.AddField(
            model_name='joke',
            name='content_tier',
            field=models.CharField(choices=[('tier_1', 'Tier 1 - Universal'), ('tier_2', 'Tier 2 - Mature'), ('tier_3', 'Tier 3 - Prohibited')], db_index=True, default='tier_1', help_text='Content classification tier for compliance', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notification_collection_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notification_daily_joke',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notification_email_digest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notification_trending_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('is_premium', models.BooleanField(default=False)),
                ('public_profile', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('share_analytics', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('offensive', 'Offensive Content'), ('inappropriate', 'Inappropriate for Rating'), ('spam', 'Spam'), ('copyright', 'Copyright Violation'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jokes.joke')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='jokes_conte_status_1364f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='jokes_favor_user_id_7be22e_idx')],
                'unique_together': {('user', 'joke')},
            },
        ),
        migrations.CreateModel(
            name='JokeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('setup', models.TextField(blank=True)),
                ('punchline', models.TextField(blank=True)),
                ('source', models.CharField(default='original', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='jokes.agerating')),
                ('context_tags', models.ManyToManyField(blank=True, related_name='submissions', to='jokes.contexttag')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='jokes.format')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='jokes.language')),
                ('published_joke', models.OneToOneField(blank=True, help_text='The published Joke record if approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='jokes.joke')),
                ('tones', models.ManyToManyField(blank=True, related_name='submissions', to='jokes.tone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='jokes_jokes_user_id_5f0fbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='jokes.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
