# Generated by Django 5.2.10 on 2026-05-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_user_profile_favorites_submissions_compliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contexttag',
            options={'verbose_name': 'Theme (ContextTag)', 'verbose_name_plural': 'Themes (ContextTags)'},
        ),
        migrations.AlterModelOptions(
            name='tone',
            options={'verbose_name': 'Category (Tone)', 'verbose_name_plural': 'Categories (Tones)'},
        ),
    ]
