# Generated by Django 5.2.10 on 2026-05-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0011_alter_contexttag_options_alter_tone_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=40)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(blank=True, help_text='Emoji shown in the picker tile (e.g. 💼)', max_length=8)),
                ('swatch_bg', models.CharField(default='#6A1CF6', help_text='Hex color for the picker tile background', max_length=20)),
                ('swatch_fg', models.CharField(default='#FFFFFF', help_text='Hex color for the picker tile text', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the picker (lower = earlier)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='vibes', to='jokes.tone')),
                ('formats', models.ManyToManyField(blank=True, related_name='vibes', to='jokes.format')),
                ('themes', models.ManyToManyField(blank=True, related_name='vibes', to='jokes.contexttag')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Future tuning hook: user can boost/dampen a vibe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vibes', to=settings.AUTH_USER_MODEL)),
                ('vibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_by', to='jokes.vibe')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='jokes_userv_user_id_7193b3_idx')],
                'unique_together': {('user', 'vibe')},
            },
        ),
    ]
