# Generated by Django 5.2.10 on 2026-05-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0013_seed_vibes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBoxRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolled_at', models.DateTimeField(auto_now_add=True)),
                ('rolled_date', models.DateField(db_index=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_pulls', to='jokes.joke')),
                ('source_vibe', models.ForeignKey(blank=True, help_text='Which vibe the roll was sourced from (null = global fallback)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jokes.vibe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_rolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rolled_at'],
                'indexes': [models.Index(fields=['user', 'rolled_date'], name='jokes_myste_user_id_3fb8a3_idx')],
            },
        ),
    ]
