# Generated by Django 5.2.10 on 2026-05-09 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0015_add_joke_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('daily', 'Daily'), ('search', 'Search'), ('explore', 'Explore'), ('mystery', 'Mystery'), ('pack', 'Pack'), ('saved', 'Saved'), ('share', 'Share'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('revealed_punchline', models.BooleanField(default=False, help_text='Did the user tap to reveal? Tracks engagement vs. bounce.')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_date', models.DateField(db_index=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='jokes_jokev_user_id_6cbee1_idx'), models.Index(fields=['user', 'viewed_date'], name='jokes_jokev_user_id_105ee3_idx'), models.Index(fields=['joke', '-viewed_at'], name='jokes_jokev_joke_id_bf8636_idx')],
            },
        ),
    ]
