# Generated by Django 5.2.10 on 2026-05-09 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0017_add_streak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_color', models.CharField(default='#FFC965', help_text='Hex color for the pack tile background', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Surface this pack as the Weekly Special on Today')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Hide until this time (null = visible immediately when published)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Hide after this time (null = never expires)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JokePackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jokes.joke')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='jokes.jokepack')),
            ],
            options={
                'ordering': ['pack', 'order'],
                'unique_together': {('pack', 'joke')},
            },
        ),
        migrations.AddField(
            model_name='jokepack',
            name='jokes',
            field=models.ManyToManyField(related_name='packs', through='jokes.JokePackEntry', to='jokes.joke'),
        ),
        migrations.CreateModel(
            name='JokePackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_entry', models.PositiveSmallIntegerField(default=0, help_text='order of the last entry the user read; 0 = not started')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='jokes.jokepack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'pack')},
            },
        ),
    ]
