# Generated by Django 5.2.10 on 2026-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0018_add_joke_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='notification_days',
            field=models.JSONField(blank=True, default=list, help_text='Weekdays the user wants the daily push: ["mon","tue",...]'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='streak_saver_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
