# Generated by Django 5.2.10 on 2026-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0019_add_ritual_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='lines',
            field=models.JSONField(blank=True, help_text='List of dialogue lines for knock-knock format; null for other formats.', null=True),
        ),
    ]
