# Generated by Django 5.2.10 on 2026-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0021_seed_demo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokesubmission',
            name='culture_tags',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='jokes.culturetag'),
        ),
        migrations.AddField(
            model_name='jokesubmission',
            name='lines',
            field=models.JSONField(blank=True, help_text='Dialogue lines for knock-knock format; null for other formats.', null=True),
        ),
    ]
