# Generated by Django 5.2.10 on 2026-06-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0022_submission_creator_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='show_mature',
            field=models.BooleanField(default=False, help_text='Adult opt-in to mature (tier_2) content. Default off. Only honored for 18+ users.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Neutral DOB for age gating (COPPA). Null = treated as non-adult.', null=True),
        ),
    ]
