# Generated by Django 5.2.10 on 2026-06-19 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0023_userpreference_show_mature_userprofile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Attributed creator, stamped at publish time. Null = legacy/seed/curated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jokes', to=settings.AUTH_USER_MODEL),
        ),
    ]
