# Generated by Django 5.2.10 on 2026-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0025_backfill_joke_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, help_text='User-chosen public @handle (lowercase alphanumeric/underscore). Null = unset.', max_length=30, null=True, unique=True),
        ),
    ]
