# Generated by Django 5.2.10 on 2026-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0026_userprofile_display_name_userprofile_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False, help_text='Removed by moderation; hidden from all users but kept for audit.'),
        ),
        migrations.AddField(
            model_name='joke',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
