# Generated by Django 5.2.10 on 2026-06-28 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0027_joke_is_removed_joke_removed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('feed', 'Feed'), ('explore', 'Explore'), ('search', 'Search'), ('daily', 'Daily'), ('pack', 'Pack'), ('other', 'Other')], default='other', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(db_index=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['joke', 'created_date'], name='jokes_jokei_joke_id_e9e8eb_idx'), models.Index(fields=['user', 'joke', 'created_date'], name='jokes_jokei_user_id_e9dbf8_idx')],
            },
        ),
    ]
