# Generated by Django 5.2.10 on 2026-06-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0028_jokeimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeDwell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwell_ms', models.PositiveIntegerField()),
                ('scroll_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='other', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(db_index=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwells', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_dwells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['joke', 'created_date'], name='jokes_joked_joke_id_d8c87b_idx')],
            },
        ),
    ]
