# Generated by Django 5.2.10 on 2026-07-20 12:19

import django.db.models.deletion
import jokes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0029_jokedwell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to=jokes.models.media_asset_path)),
                ('poster', models.ImageField(blank=True, upload_to=jokes.models.media_asset_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_gif', models.BooleanField(default=False)),
                ('safesearch', models.JSONField(blank=True, null=True)),
                ('phash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JokeSubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jokes.jokesubmission')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_links', to='jokes.mediaasset')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'position'), name='uniq_submission_media_position')],
            },
        ),
        migrations.CreateModel(
            name='JokeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jokes.joke')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_links', to='jokes.mediaasset')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('joke', 'position'), name='uniq_joke_media_position')],
            },
        ),
    ]
