# Generated by Django 5.2.10 on 2026-07-22 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0032_seed_video_audio_formats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_ms', models.PositiveIntegerField()),
                ('watch_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='other', max_length=16)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['joke', 'watched_at'], name='jokes_jokew_joke_id_288c41_idx')],
            },
        ),
    ]
