# Generated by Django 5.2.10 on 2026-07-23 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0033_jokewatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('takedown', 'Takedown'), ('rejection', 'Rejection')], max_length=10)),
                ('reason_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('reversed', 'Reversed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('joke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='jokes.joke')),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='jokes.jokesubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('joke__isnull', False), ('submission__isnull', True)), models.Q(('joke__isnull', True), ('submission__isnull', False)), _connector='OR'), name='appeal_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'joke'), name='uniq_pending_appeal_per_user_joke'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'submission'), name='uniq_pending_appeal_per_user_submission')],
            },
        ),
    ]
