# Generated by Django 5.2.10 on 2026-07-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0034_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
