# Generated by Django 5.2.10 on 2026-08-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0035_mediaasset_quarantined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creator_milestone_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_digest_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
