# Generated by Django 5.2.17 on 2026-09-27 12:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0037_impression_daily_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokeimpression', name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jokedwell', name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jokewatch', name='watched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='AnalyticsConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('policy_version', models.CharField(max_length=48)),
                ('provenance', models.CharField(choices=[('legacy_observed', 'Previously existing preference observed'), ('preference', 'Explicit preference transition')], max_length=24)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_consent_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudienceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('legacy', 'Unknown legacy client')], max_length=8)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('reveal', 'Reveal'), ('dwell', 'Dwell'), ('watch', 'Watch')], max_length=12)),
                ('source', models.CharField(max_length=16)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_version', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eligibility', models.CharField(default='adult_opt_in_at_receipt', max_length=32)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jokes.analyticsconsentrecord')),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_events', to='jokes.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='analyticsconsentrecord',
            index=models.Index(fields=['user', 'recorded_at'], name='jokes_analy_user_id_a01283_idx'),
        ),
        migrations.AddIndex(
            model_name='audienceevent',
            index=models.Index(fields=['user', 'received_at'], name='jokes_audie_user_id_3b317d_idx'),
        ),
        migrations.AddIndex(
            model_name='audienceevent',
            index=models.Index(fields=['joke', 'event_type', 'received_at'], name='jokes_audie_joke_id_a6fd41_idx'),
        ),
        migrations.AddConstraint(
            model_name='audienceevent',
            constraint=models.UniqueConstraint(fields=('user', 'event_id'), name='audience_event_user_event_uniq'),
        ),
    ]
