# Generated by Django 5.2.17 on 2026-09-27 13:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0038_versioned_audience_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='culturetag',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='cultures', to='jokes.language'),
        ),
        migrations.AddField(
            model_name='culturetag',
            name='native_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joke',
            name='cultural_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='editorial_status',
            field=models.CharField(choices=[('legacy', 'Legacy content'), ('generated', 'AI generated'), ('native_reviewed', 'Reviewed by a native speaker')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='joke',
            name='search_vector_simple',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='seed_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='joke',
            trigger=pgtrigger.compiler.Trigger(name='joke_simple_search_update', sql=pgtrigger.compiler.UpsertTriggerSql(execute='tsvector_update_trigger("search_vector_simple", "pg_catalog.simple", "text", "setup", "punchline")', func='', hash='a0f274db6692dcaab64ddf0e182a20fc895898a6', operation='INSERT OR UPDATE OF "text", "setup", "punchline"', pgid='pgtrigger_joke_simple_search_update_8592e', table='jokes_joke', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='culturetag',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='cultures', to='jokes.country'),
        ),
        migrations.AddField(
            model_name='joke',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='jokes', to='jokes.country'),
        ),
        migrations.AddField(
            model_name='jokesubmission',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='jokes.country'),
        ),
        migrations.AddIndex(
            model_name='joke',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_simple'], name='joke_simple_search_idx'),
        ),
    ]
