# Generated by Django 5.2.17 on 2026-10-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0042_discovery_collection_triples'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='origin_country',
            field=models.ForeignKey(blank=True, help_text='Country the joke comes from (nationality), not a country it is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_jokes', to='jokes.country'),
        ),
        migrations.AlterField(
            model_name='joke',
            name='editorial_status',
            field=models.CharField(choices=[('legacy', 'Legacy content'), ('generated', 'AI generated (held)'), ('ai_screened', 'AI generated, screened'), ('native_reviewed', 'Reviewed by a native speaker')], db_index=True, default='legacy', max_length=20),
        ),
    ]
