# Generated by Django 5.2.10 on 2026-08-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_digestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestrun',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
